################### Common Part
# GPU
use_cuda: True # Use gpu by default unless it isn't available
device_num: 0 # CUDA device number

# Ray
num_cpus: 4
num_gpus: 1

# Etc
epsilon: 0.0000001

# Optimizer
optim_betas : [0.9, 0.999] # Adam alpha -> beta1, beta2
optim_eps: 0.00001 # Adam epsilon
torch_deterministic: True

# Environment
env_wrapper: 'opengym'
env_name: 'AntBulletEnv-v0'
n_envs: 4
distributed_processing_type: "sync"  # {sync, async}

# Rendering
render: False

# Inference
training_mode : True
inference_model_path: ""
inference_max_episodes: 100         # maximum number of episodes

# Logging options
log_interval: 4000 # Log summary of stats after every {} time steps
use_tensorboard: True # Log results to tensorboard

# Checkpoint
save_model: True # Save the models to disk
save_model_interval: 100000 # Save models after this many steps
checkpoint_path: ""
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
local_results_path: "results" # Path for local results

################### Training Part
# Training Steps
max_environment_steps: 3000000          # maximum environment steps
n_steps: 500
n_episodes: 0
n_epochs: 5 #  update policy for n epochs in one leaner update
batch_size: 64 # Number of samples to train

# Learning Rate
lr_policy: 0.00025       # learning rate for actor network 0.00025
lr_critic: 0.001         # learning rate for critic network 0.001

# Learning Rate Annealing
lr_annealing: True

# Warming Up step
warmup_step: 0

# Epsilon greedy noise
epsilon_greedy: False

# Gradient Clipping
grad_norm_clip: 0.45 # Reduce magnitude of gradients above this L2 norm

# PPO Clipping
ppo_clipping_epsilon: 0.1          # clip parameter for PPO
clip_schedule: True

# discount factor
gamma: 0.99            # discount factor

# Return and Advantage
advantage_type: 'gae'
return_standardization: True
gae_standardization: True
gae_lambda: 0.95

# loss
vloss_coef: 0.5
eloss_coef: 0.01

# Network Hidden dims
actor_hidden_dims: [64, 64, 64]
critic_hidden_dims: [64, 64, 64]