################### Common Part
# GPU
use_cuda: True # Use gpu by default unless it isn't available
device_num: 0 # CUDA device number

# Etc
epsilon: 0.0000001

# Optimizer
optim_betas : [0.9, 0.999] # Adam alpha -> beta1, beta2
optim_eps: 0.00001 # Adam epsilon
torch_deterministic: True

# Environment
env_wrapper: 'opengym'
env_name: 'LunarLanderContinuous-v2'
n_envs: 1

# Rendering
render: False

# Inference
training_mode : True
inference_model_path: ""  # Inference by reading the model in the specified file path in inference mode
inference_max_episodes: 100         # maximum number of episodes

# Logging options
log_interval: 2000 # Log summary of stats after every {} time steps
use_tensorboard: True # Log results to tensorboard

# Checkpoint
save_model: False # Save the models to disk
save_model_interval: 20000 # Save models after this many steps
checkpoint_path: ""
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
local_results_path: "results" # Path for local results

################### Training Part
# Training Steps
max_environment_steps: 1000000          # maximum environment steps
n_steps: 8192   #16384
n_episodes: 0
n_epochs: 4 #  update policy for n epochs in one leaner update 4
batch_size: 64 # Number of samples to train

# Learning Rate
lr_policy: 0.00002       # learning rate for actor network
lr_critic: 0.0002        # learning rate for critic network
# Learning Rate Annealing
lr_annealing: True

# Warming Up step
warmup_step: 0

# Epsilon greedy noise
epsilon_greedy: False

# Gradient Clipping
grad_norm_clip: 0.5 # Reduce magnitude of gradients above this L2 norm

# discount factor
gamma: 0.999            # discount factor

# GAE
advantage_type: 'gae' # {n_step, gae, mc}
n_steps_of_return: 20
return_standardization: True
gae_standardization: True
gae_lambda: 0.98

# loss
vloss_coef: 0.5
eloss_coef: 0.01

# Network Hidden dims
actor_hidden_dims: [512]
critic_hidden_dims: [512]
